"""
Django settings for mblog project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from pathlib import Path
import os  # 用于环境变量和路径处理
import pymysql

# 配置MySQL驱动
pymysql.install_as_MySQLdb()

# 项目根目录
BASE_DIR = Path(__file__).resolve().parent.parent


# 安全设置
# 生产环境必须通过环境变量设置密钥
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-+h09d69)x82uf(^ku=gmbrn&4^3gx9lq0l#23^edw$9$evb2m^')

# 生产环境禁用调试模式
DEBUG = True

# 允许访问的主机列表
# 如果你是本地开发测试（比如用 127.0.0.1 或 localhost 访问）
ALLOWED_HOSTS = ['39.104.71.209', 'localhost', '127.0.0.1']

# 临时测试也可以用通配符（生产环境不推荐）
# ALLOWED_HOSTS = ['*']


# 应用配置
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mysite',  # 自定义应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 模板文件夹路径
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mblog.wsgi.application'


# 数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # 指向你的原始SQLite文件
    }
}


# 密码验证
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # 修正此处路径
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # 修正此处路径
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 国际化配置
LANGUAGE_CODE = 'zh-hans'  # 简体中文
TIME_ZONE = 'Asia/Shanghai'  # 上海时区
USE_I18N = True
USE_L10N = True
USE_TZ = True  # 启用时区支持


# 静态文件配置
STATIC_URL = '/static/'  # URL路径
STATIC_ROOT = BASE_DIR / 'staticfiles'  # 静态文件收集目录

# 额外的静态文件目录（如果需要）
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# 默认主键类型
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 生产环境安全增强设置
if not DEBUG:
    # 临时时注释掉 HTTPS 相关配置
    # SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # SECURE_SSL_REDIRECT = True  # 注释掉这行，避免强制跳转 HTTPS
    # SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'